import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Daniel Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Daniel Laera Blog</a>
        </h1>
      </main>
    </div>
  );
}
